version: 1
build:
  binary: razord
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 100000000uatom
  - 100000000000000000000qrzr
- name: bob
  coins:
  - 5000000000000qrzr
faucet:
  name: bob
  coins:
  - 10qrzr
  host: 0.0.0.0:4500
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: qrzr
    evm:
      params:
        evm_denom: qrzr
    gov:
      deposit_params:
        min_deposit:
        - amount: "10000000"
          denom: qrzr
    mint:
      params:
        mint_denom:  qrzr
    staking:
      params:
        bond_denom:  qrzr
  chain_id: razor_44117-1
validators:
- name: alice
  bonded: 100000000000000000000qrzr
  app:
    evm-rpc:
      address: 0.0.0.0:8545
      ws-address: 0.0.0.0:8546
  home: $HOME/.razord
